### ISSUE TITLE
Can we just import the VueLocalStorage class?

### ISSUE THREAD

**Issue by tibineagu** [pinguinjkeke/vue-local-storage#13]
First off - great project, really love the idea behind the implementation.

It would be great if we could only use your [`VueLocalStorage`](https://github.com/pinguinjkeke/vue-local-storage/blob/master/src/VueLocalStorage.js) class in projects. The way the mixin is implemented is a bit off for our needs, but the class it's using is _spot on_.

Any idea how we could do this?

**Comment by pinguinjkeke** [comment]
Hello, @tibineagu!

Yes, you can use it by directly importing it from src directory. Or there other better ability to provide it (maybe somehow via package.json configuration, idk)?
If you are using classic setup with babel with ignored node_modules directory, you should modify exclude rule for babel because it should not ignore VueLocalStorage class file.
You can watch example in vue-admin project (all vue-bulma packages are not ignored by the babel).

https://github.com/vue-bulma/vue-admin/blob/master/build/webpack.base.conf.js#L65

**Comment by tibineagu** [comment]
Hey @pinguinjkeke 

Thanks for getting back to me so soon! I'll try to implement your solution.

Originally I was thinking something along the lines of how this library lets you [import files with different functionalities](https://github.com/stefanpenner/es6-promise#auto-polyfill):

If you look at the readme, you can either `import 'es6-polyfill'` or `import 'es6-polyfill/auto'` (the latter comes from [a different file](https://github.com/stefanpenner/es6-promise/tree/master/lib))

I'm quite new at this so I'm not exactly sure how they're doing it.

**Comment by pinguinjkeke** [comment]
@tibineagu you was like: "Man, it's great you remind me so fast"... *Reminds in 10 days*

I have read about files section in package.json, i'll try to implement it tomorrow ;)
